server:
  port: 8000
  servlet:
    context-path: /spring
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/students
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true